import GlobalContextProvider from "@/context";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import SidebarMain from "@/components/sidebar/SidebarMain";
import HeaderMain from "@/components/header/HeaderMain";
import NextAuthProvider from '@/providers/auth-provider';


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<body className={inter.className}>
      <NextAuthProvider>
          <GlobalContextProvider>
            <div className="flex h-screen overflow-hidden">
              <SidebarMain />

              <div className="relative flex flex-1 flex-col overflow-y-auto overflow-x-hidden">
                <HeaderMain />
                <main>
                  <div className="mx-auto max-w-screen-2xl p-4 md:p-6 2xl:p-10">
                    {children}
                  </div>
                </main>
              </div>
            </div>
          </GlobalContextProvider>
        </NextAuthProvider>
			</body>
		</html>
	);
}
